import Image from "next/image";
import { Controller, Scene } from "react-scrollmagic";
import { Tween, Timeline } from "react-gsap";

import FirstSection from "../components/sections/FirstSection";
import Arch from "../components/three/Arch";
import SecoundSection from "../components/sections/SecoundSection";
import ForthSection from "../components/sections/ForthSection";
import FifthSection from "../components/sections/FifthSection";
import ThirdSection from "../components/sections/ThirdSection";
import IntroSection from "../components/sections/IntroSection";
import Introtwo from "../components/sections/Introtwo";
import SocialMedia from "../components/sections/SocialMedia";
import ContactSection from "../components/sections/ContactSection";
import ThreeRowSection from "../components/sections/ThreeRowSection";
import MarqueeSection from "../components/sections/MarqueeSection";
import Head from "next/head";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Ayad Al-Shaikhli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link
          href="https://fonts.googleapis.com/css2?family=Gulzar&family=Kufam&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntroSection />
      {/* <Introtwo /> */}
      <Arch />
      <FirstSection />

      <SecoundSection />
      <ThirdSection />

      <ThreeRowSection />
      <FifthSection />
      <ForthSection />

      <SocialMedia />
      <ContactSection />
    </>
  );
}
